language: python

services: 
  - redis-server

python:
  - 3.5
  - 3.6

env:
  global:
    - PYTHONPATH="/home/travis/build/synw/django-mqueue"

install:
  - pip install virtualenv tox coveralls

script:
  - tox

after_success:
  coveralls
