# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-14 12:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obj_pk', models.IntegerField(blank=True, null=True, verbose_name='Object primary key')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('url', models.CharField(blank=True, max_length=255, verbose_name='Url')),
                ('admin_url', models.CharField(blank=True, max_length=255, verbose_name='Admin url')),
                ('notes', models.TextField(blank=True)),
                ('date_posted', models.DateTimeField(auto_now_add=True, verbose_name='Date posted')),
                ('event_class', models.CharField(blank=True, max_length=120, verbose_name='Class')),
                ('request', models.TextField(blank=True, verbose_name='Request')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='Content type')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'ordering': ['-date_posted'],
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'permissions': (('view_mevent', 'Can see Events'),),
            },
        ),
    ]
