# Generated by Django 3.1.4 on 2021-02-21 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obj_pk', models.IntegerField(blank=True, null=True, verbose_name='Object primary key')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('url', models.CharField(blank=True, max_length=255, verbose_name='Url')),
                ('admin_url', models.CharField(blank=True, max_length=255, verbose_name='Admin url')),
                ('notes', models.TextField(blank=True)),
                ('date_posted', models.DateTimeField(auto_now_add=True, verbose_name='Date posted')),
                ('event_class', models.CharField(blank=True, max_length=120, verbose_name='Class')),
                ('request', models.TextField(blank=True, verbose_name='Request')),
                ('bucket', models.CharField(blank=True, max_length=60, verbose_name='Bucket')),
                ('data', models.TextField(blank=True, verbose_name='Data')),
                ('scope', models.CharField(choices=[('superuser', 'Superuser'), ('staff', 'Staff'), ('users', 'Users'), ('public', 'Public')], default='superuser', max_length=18, verbose_name='Scope')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='Content type')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['-date_posted'],
            },
        ),
    ]
