# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqueue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mevent',
            name='scope',
            field=models.CharField(choices=[('superuser', 'Superuser'), ('staff', 'Staff'), ('users', 'Users'), ('user', 'User'), ('public', 'Public')], default='superuser', max_length=18, verbose_name='Scope'),
        ),
    ]
