# Generated by Django 5.2.1 on 2025-06-06 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqueue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mevent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
